title: Arnaud Dionne
email: you@example.com
description: >-
  A base GitHub Pages site built with the Architect theme.
baseurl: ""
url: "https://ciementine123.github.io"
theme: jekyll-theme-architect
show_downloads: false
